-- MySQL Script generated by MySQL Workbench
-- Thu Feb 18 20:20:41 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema buaps_unisdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema buaps_unisdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `buaps_unisdb` DEFAULT CHARACTER SET utf8 ;
USE `buaps_unisdb` ;

-- -----------------------------------------------------
-- Table `buaps_unisdb`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buaps_unisdb`.`tb_usuario` (
  `matricula` VARCHAR(9) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `rol` INT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buaps_unisdb`.`tb_horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buaps_unisdb`.`tb_horario` (
  `id_horario` INT NOT NULL AUTO_INCREMENT,
  `maestro_fk` INT NOT NULL,
  `dia` INT NULL,
  `hora_inicio` TIME NULL,
  `hora_fin` TIME NULL,
  `tb_usuario_matricula` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id_horario`, `tb_usuario_matricula`),
  INDEX `fk_tb_horario_tb_usuario1_idx` (`tb_usuario_matricula` ASC),
  CONSTRAINT `fk_tb_horario_tb_usuario1`
    FOREIGN KEY (`tb_usuario_matricula`)
    REFERENCES `buaps_unisdb`.`tb_usuario` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buaps_unisdb`.`tb_materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buaps_unisdb`.`tb_materia` (
  `id_materias` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `status_fk` VARCHAR(45) NULL,
  PRIMARY KEY (`id_materias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buaps_unisdb`.`tb_statusMateria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buaps_unisdb`.`tb_statusMateria` (
  `status` VARCHAR(20) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buaps_unisdb`.`tb_asesoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buaps_unisdb`.`tb_asesoria` (
  `asesoria` INT NOT NULL AUTO_INCREMENT,
  `horario_fk` INT NULL,
  `materia_fk` INT NULL,
  `status` INT NULL,
  `date` DATETIME NULL,
  `places` INT NULL,
  `tb_horario_id_horario` INT NOT NULL,
  `tb_materia_id_materias` INT NOT NULL,
  `tb_statusMateria_status` VARCHAR(20) NOT NULL,
  `tb_usuario_matricula` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`asesoria`, `tb_horario_id_horario`, `tb_materia_id_materias`, `tb_statusMateria_status`, `tb_usuario_matricula`),
  UNIQUE INDEX `asesoria_UNIQUE` (`asesoria` ASC),
  INDEX `fk_tb_asesoria_tb_horario_idx` (`tb_horario_id_horario` ASC),
  INDEX `fk_tb_asesoria_tb_materia1_idx` (`tb_materia_id_materias` ASC),
  INDEX `fk_tb_asesoria_tb_statusMateria1_idx` (`tb_statusMateria_status` ASC),
  INDEX `fk_tb_asesoria_tb_usuario1_idx` (`tb_usuario_matricula` ASC),
  CONSTRAINT `fk_tb_asesoria_tb_horario`
    FOREIGN KEY (`tb_horario_id_horario`)
    REFERENCES `buaps_unisdb`.`tb_horario` (`id_horario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_asesoria_tb_materia1`
    FOREIGN KEY (`tb_materia_id_materias`)
    REFERENCES `buaps_unisdb`.`tb_materia` (`id_materias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_asesoria_tb_statusMateria1`
    FOREIGN KEY (`tb_statusMateria_status`)
    REFERENCES `buaps_unisdb`.`tb_statusMateria` (`status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_asesoria_tb_usuario1`
    FOREIGN KEY (`tb_usuario_matricula`)
    REFERENCES `buaps_unisdb`.`tb_usuario` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buaps_unisdb`.`tb_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buaps_unisdb`.`tb_roles` (
  `clave` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `tb_usuario_matricula` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`clave`, `tb_usuario_matricula`),
  INDEX `fk_tb_roles_tb_usuario1_idx` (`tb_usuario_matricula` ASC),
  CONSTRAINT `fk_tb_roles_tb_usuario1`
    FOREIGN KEY (`tb_usuario_matricula`)
    REFERENCES `buaps_unisdb`.`tb_usuario` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
